### PR TITLE
Gs.info check

### PR DESCRIPTION
**Pull request by Rampriya-S**
This pull request contains Script only check to find gs.log() in Client scripts, Business rules and Script includes.

### CODE REVIEW

**Comment by niamccash** [comment]
Thanks for your submission. It appears that this pull request still contains more files than described in the title. Please review and update the pull request to either remove the extra/unintended files or to update the description to be more comprehensive. Ensure your contributions are meaningful and adhere to the project’s standards. You can create a new branch on your forked repository to avoid accidental inclusions of new commits in the future. You also didn't add to the readme.md file as I requested in my last feedback. Closing this. Once you make additional changes, feel free to re-open this Pull Request or create a new one.

**Comment by Rampriya-S** [comment]
@niamccash I have created new branch, but still it is pulling multiple files. I want to submit https://github.com/ServiceNowDevProgram/example-instancescan-checks/pull/140/files#diff-0e7ff7f7aa46c0b21b6412606b8de117c2bfff63aec0a7fb684e88ea34ad3ec2

file alone. Could you please delete the rest for me>

**Comment by Rampriya-S** [comment]
@niamccash Can you please help me how to remove the unnecessary files?

**Comment by niamccash** [comment]
Here's what I'd recommend... 
In your master branch, sync your fork to get it up to date with the latest version that's already approved in the ServiceNow Dev program account: 
image

Update your instance with the master branch and stash any work in progress you might have.
Then create a NEW branch, and add the instance check you want to submit.

**Comment by Rampriya-S** [comment]
@niamccash Thanks for your advice. It's working.

**Pull request closed without merging**
