### PR TITLE
Added checks for tables (sys_choice, sys_user) that should not be extended

### PR DESCRIPTION
**Pull request by niamccash**

### CODE REVIEW

**Comment by phifogg** [comment]
Can you add/document your checks in the readme.md file? Thanks!

**Comment by niamccash** [comment]
Whoops, forgot. README.md updated

**Comment by phifogg** [comment]
Are you sure on this one?
### User table should not be extended

I believe the CSM module does extend this table for consumers.

**Comment by niamccash** [comment]
There is no official documentation around that which I can find but it was mentioned by Cory Seering who I believe is a ServiceNow employee. I tried to documented it on the community https://community.servicenow.com/community?id=community_article&sys_id=d8e645a2dbadf810da1999ead3961964. Here's a similar post: https://jace.pro/post/2021-08-12-extending-user-is-bad/

But I understand if it's questionable and can certainly remove it.

**Comment by niamccash** [comment]
User table extension check removed - moved to `author_elective_update` folder in the repo since it was deleted

**Comment by phifogg** [comment]
I had a look at the links provided... good arguments indeed. I am ok for you to include this check again with links to these - appologies if you had the links already and I missed them.

**Comment by niamccash** [comment]
Thanks Daniel. User table check restored to this pull request.

**Pull request merged**
