### PR TITLE
Adds a new instance check to notify about the possible risk associated with the usage of setWorkflow(false) method in business rule

### PR DESCRIPTION
**Pull request by aswamy93**
As setWorkflow(false) method will stop the execution of business rules on that particular GlideRecord object, this will result in unexpected behaviour where the execution of business rules skipped. Maintain caution while using this method and perform regression testing to avoid possible risk. It can have noticeable impact on Audit, Journal fields, notifications, SLA engine, workflow, flow engine etc.,

### CODE REVIEW

**Comment by niamccash** [comment]
hi @aswamy93 Thank you for your contribution. Looks good. Could you please update the readme file to include a description of your newly added check so that other people contributing know that it's there and don't duplicate?

**Comment by aswamy93** [comment]
> hi @aswamy93 Thank you for your contribution. Looks good. Could you please update the readme file to include a description of your newly added check so that other people contributing know that it's there and don't duplicate?

Hi @niamccash 
Many thanks for the review,. I have update the readme file and created another pull request: https://github.com/ServiceNowDevProgram/example-instancescan-checks/pull/120. Please check it when you get a chance

**Comment by niamccash** [comment]
hi @aswamy93 
Can you please add the readme changes to this same PR? I think you should be able to go into your new_addition branch and update the readme file in that same branch to update this PR.

**Comment by aswamy93** [comment]
> hi @aswamy93 Can you please add the readme changes to this same PR? I think you should be able to go into your new_addition branch and update the readme file in that same branch to update this PR.

Hi @niamccash , There is no option to merge pull requests. Though I switched to new_addition brand updated readme but looks like I created another pull request. Sorry for the multiple pull requests for the same one.

**Comment by niamccash** [comment]
How are you editing the readme file - in the browser or on your local computer? Can you try to go to https://github.com/aswamy93/example-instancescan-checks/tree/new_addition and edit the readme file there and commit? 

It looks like you weren't working in the new_addition branch for your new PR. It was a new branch altogether.

**Comment by aswamy93** [comment]
> How are you editing the readme file - in the browser or on your local computer? Can you try to go to https://github.com/aswamy93/example-instancescan-checks/tree/new_addition and edit the readme file there and commit?
> 
> It looks like you weren't working in the new_addition branch for your new PR. It was a new branch altogether.

Hi @niamccash , Sorry, my bad. I followed your steps and committed the changes without creating pull requests. Now, I can see that the readme file is captured in this pull requests. Thank you so much for your help

**Comment by SapphicFire** [comment]
Addressed checksum conflict - will leave ownership of PR review and merge with Nia :)

**Comment by niamccash** [comment]
Thanks for the help @SapphicFire!

**Pull request merged**
