### PR TITLE
Instance scan check to identify slow jobs in transaction logs.

### PR DESCRIPTION
**Pull request by selvarun-umass**
Purpose:
This Instance Scan Check is a table check scan that enables administrators to investigate transaction logs in ServiceNow to diagnose performance issues reported by users. This check specifically identifies transactions with a Response Time greater than 120 seconds, helping to uncover performance bottlenecks, understand user behavior, and track down issues within a specific time frame.

In our organization, this check has proven extremely valuable, especially when addressing slow performance in our DEV instance. By analyzing the transaction logs, we were able to pinpoint and resolve critical issues, significantly improving overall system performance.

### CODE REVIEW

**Comment by niamccash** [comment]
Thanks for your contribution. Looks like a good instance scan. But it seems you've modified the wrong readme.md file. 
Can you please add your description to the root readme.md file instead of the one in the ca8467c41b9abc10ce0f62c3b24bcbaa/ folder?

**Comment by selvarun-umass** [comment]
@niamccash, I have updated the READMe.md file as per your advice, could you please check if it looks good? Thank you so much for your kind support and for your feedback.

**Comment by niamccash** [comment]
Great! Thanks for updating!

**Comment by selvarun-umass** [comment]
@niamccash Thank you so much for merging it:)

**Pull request merged**
