### PR TITLE
Check the incidents that are closed or canceled but still active

### PR DESCRIPTION
**Pull request by Iuliak**
A sign that the close_states are not set correctly on the incident table. This check can be done on any table, especially there where the State model was changed from OOTB or for custom extended tables. The problem with this kind of records is that they can influence the reports on active records on the respective table.
It is a simple table instance check.

### CODE REVIEW

**Comment by niamccash** [comment]
@Iuliak Can you please add a description of the check to the readme file as part of this PR?

**Comment by Iuliak** [comment]
[Readme.md](https://github.com/ServiceNowDevProgram/example-instancescan-checks/files/12891234/Readme.md)
Hi @niamccash,
 is it ok like this?
Thank you!

**Comment by SapphicFire** [comment]
That content is good. It just needs to be added to the repository readme.md file under the appropriate category as another commit, with a heading as per the other entries 😃

**Comment by Iuliak** [comment]
Ah ok, done :) hopefully :D

**Comment by niamccash** [comment]
@Iuliak Great description of the check. Good job! Could you please move the description in the readme to the appropriate category section? The readme file has different sections for different categories of Instance Scan. 

I see the scan you created is under the **Manageability** category but the description in the readme was put under the **User Experience** category.

**Comment by Iuliak** [comment]
@niamccash yes, sorry .. I think its ok now.

**Comment by niamccash** [comment]
@Iuliak no apologies needed. It happens. Thank you for updating. Looks great! PR accepted!

**Pull request merged**
