### PR TITLE
Check gs.log in script

### PR DESCRIPTION
**Pull request by Rampriya-S**
This pull request contains Script only check to find gs.log() in Client scripts, Business rules and Script includes.

### CODE REVIEW

**Review by SapphicFire — CHANGES_REQUESTED** [review]
Thanks for your submission. It appears that this pull request contains more files than described in the title. Please review and update the pull request to either remove the extra/unintended files or to update the description to be more comprehensive. Ensure your contributions are meaningful and adhere to the project’s standards. You can create a new branch on your forked repository to avoid accidental inclusions of new commits in the future. Closing this for now. Once you make additional changes, feel free to re-open this Pull Request or create a new one.

Additionally, please refer to the contributing guidelines as this has not been followed with regard to descriptions.

**Comment by Rampriya-S** [comment]
Hi @SapphicFire could you please help me how to remove extra/unintended files, It automatically pulls multiple files than I am committing, please help to fix this.

**Comment by Rampriya-S** [comment]
I think I don't have enough permissions to delete unnecessary files during the commit pull request, please provide me if possible.

**Comment by SapphicFire** [comment]
Hi @Rampriya-S - to do this you create a separate branch and make the separate records in that branch

**Pull request closed without merging**
